In [1]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.preprocessing import MinMaxScaler

dummy_employed = pd.read_csv('dummy_employed.csv')
dummy_wk_incomes = pd.read_csv('dummy_wk_incomes.csv')

In [2]:
y = dummy_employed['Monthly Income']
X = dummy_employed.drop(columns=['Monthly Income'], axis=1)

scaler = MinMaxScaler()
X=pd.DataFrame(scaler.fit_transform(X),
            columns=X.columns, index=X.index)

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

rt = DecisionTreeRegressor(criterion = 'mse', max_depth=100, min_samples_split=8, splitter='best', min_samples_leaf= 100)

model_r = rt.fit(X_train, y_train)

y_pred = model_r.predict(X_test)

from sklearn import tree
from sklearn.tree import export_graphviz
dot_data = tree.export_graphviz(rt, 
                  feature_names=list(X),  
                  class_names=sorted(y.unique()),  
                  filled=True, rounded=True,  
                  special_characters=True,
                   out_file=None,
                           )
graph = graphviz.Source(dot_data)
graph

In [4]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R Squared Score is:', r2_score(y_test, y_pred))

Mean Absolute Error: 2927.019725719349
Mean Squared Error: 30537755.371197402
Root Mean Squared Error: 5526.097662111791
R Squared Score is: 0.18134664395291678

In [5]:
y = dummy_wk_incomes['Monthly Income']
X = dummy_wk_incomes.drop(columns=['Monthly Income'], axis=1)

scaler = MinMaxScaler()
X=pd.DataFrame(scaler.fit_transform(X),
            columns=X.columns, index=X.index) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

rt = DecisionTreeRegressor(min_samples_split=8, max_depth=100, splitter='best', min_samples_leaf= 100)

model_r = rt.fit(X_train, y_train)

y_pred = model_r.predict(X_test)

In [6]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R Squared Score is:', r2_score(y_test, y_pred))

Mean Absolute Error: 3369.507344612625
Mean Squared Error: 39766029.669677876
Root Mean Squared Error: 6306.0312138204545
R Squared Score is: 0.2685455500527367

##  Linear Multiple Regression

In [7]:
import statsmodels.api as sm

model = sm.OLS(y, sm.add_constant(X))
results = model.fit()

print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         Monthly Income   R-squared:                       0.273
Model:                            OLS   Adj. R-squared:                  0.272
Method:                 Least Squares   F-statistic:                     215.9
Date:                Wed, 29 Mar 2023   Prob (F-statistic):               0.00
Time:                        18:02:53   Log-Likelihood:            -1.2815e+06
No. Observations:              126055   AIC:                         2.563e+06
Df Residuals:                  125835   BIC:                         2.566e+06
Df Model:                         219
Covariance Type:            nonrobust
========================================================================================================================================================================================================
                                                                                                                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
const                                                                                                                                 1.335e+04    518.126     25.775      0.000    1.23e+04    1.44e+04
Unnamed: 0                                                                                                                             -77.7130    157.736     -0.493      0.622    -386.872     231.446
Age                                                                                                                                   1769.1738    138.171     12.804      0.000    1498.362    2039.986
Gender_Mujer                                                                                                                         -2053.5135     39.765    -51.642      0.000   -2131.451   -1975.576
Literacy_Sí                                                                                                                            558.1614    409.054      1.365      0.172    -243.577    1359.900
Scholarship_Doctorado                                                                                                                 1.183e+04    368.399     32.101      0.000    1.11e+04    1.25e+04
Scholarship_Maestría                                                                                                                  7553.9243    203.684     37.087      0.000    7154.708    7953.141
Scholarship_Normal                                                                                                                     716.9647    629.484      1.139      0.255    -516.813    1950.742
Scholarship_Preparatoria o bachillerato                                                                                                520.2518     56.225      9.253      0.000     410.053     630.451
Scholarship_Primaria                                                                                                                 -1318.3871     59.169    -22.282      0.000   -1434.357   -1202.417
Scholarship_Profesional                                                                                                               2669.1518    136.038     19.621      0.000    2402.519    2935.785
Scholarship_Secundaria                                                                                                                -485.8602     54.317     -8.945      0.000    -592.320    -379.400
Career_Administración en el ámbito de la ingeniería y la construcción                                                                 -485.7435    472.716     -1.028      0.304   -1412.259     440.773
Career_Administración en los campos de la educación, salud, deporte, agronomía y las artes y humanidades                             -1665.7970    863.384     -1.929      0.054   -3358.016      26.422
Career_Administración pública                                                                                                          574.0608    652.257      0.880      0.379    -704.351    1852.472
Career_Administración turística y de restaurantes                                                                                      335.3845    565.406      0.593      0.553    -772.801    1443.570
Career_Adquisición de idiomas extranjeros                                                                                            -1047.4720    489.754     -2.139      0.032   -2007.382     -87.562
Career_Anestesiología                                                                                                                 7349.3125   1496.229      4.912      0.000    4416.729    1.03e+04
Career_Arquitectura y urbanismo                                                                                                        536.8562    281.422      1.908      0.056     -14.726    1088.439
Career_Artes escénicas                                                                                                               -1865.9696   1266.460     -1.473      0.141   -4348.209     616.270
Career_Artesanía tradicional y manualidades                                                                                          -2393.9356   4456.170     -0.537      0.591   -1.11e+04    6340.082
Career_Atención prehospitalaria y emergencias médicas                                                                                 -669.9728   1245.599     -0.538      0.591   -3111.325    1771.379
Career_Audiología y foniatría                                                                                                        -6722.9356   4458.170     -1.508      0.132   -1.55e+04    2015.000
Career_Audiometría y optometría                                                                                                       -439.2508   1320.411     -0.333      0.739   -3027.234    2148.733
Career_Bellas artes                                                                                                                  -3257.1170    874.998     -3.722      0.000   -4972.098   -1542.136
Career_Biblioteconomía y archivonomía                                                                                                -1091.0217   1631.728     -0.669      0.504   -4289.181    2107.138
Career_Biología                                                                                                                      -1097.4254    474.165     -2.314      0.021   -2026.780    -168.071
Career_Biomedicina                                                                                                                    3653.9116   2233.065      1.636      0.102    -722.857    8030.680
Career_Bioquímica y biofísica                                                                                                          365.8204    406.646      0.900      0.368    -431.199    1162.840
Career_Campo de formación académica no especificado                                                                                    494.5265    678.914      0.728      0.466    -836.133    1825.186
Career_Cardiología                                                                                                                    1.231e+04   6301.794      1.954      0.051     -36.801    2.47e+04
Career_Ciencias computacionales                                                                                                       -409.5108    469.229     -0.873      0.383   -1329.192     510.170
Career_Ciencias de la educación                                                                                                      -1369.4731    246.605     -5.553      0.000   -1852.815    -886.131
Career_Ciencias de la tierra y de la atmósfera                                                                                        1785.6167    970.168      1.841      0.066    -115.897    3687.130
Career_Ciencias políticas                                                                                                              820.1168    493.843      1.661      0.097    -147.807    1788.041
Career_Cirugía general                                                                                                                2920.5141   1909.395      1.530      0.126    -821.867    6662.895
Career_Cirugía oral y maxilofacial                                                                                                   -7051.6784   6301.739     -1.119      0.263   -1.94e+04    5299.623
Career_Cirugía plástica estética y reconstructiva                                                                                     1.906e+04   3155.985      6.041      0.000    1.29e+04    2.53e+04
Career_Comunicación y periodismo                                                                                                        73.8967    349.608      0.211      0.833    -611.328     759.121
Career_Construcción e ingeniería civil                                                                                                1442.1391    263.728      5.468      0.000     925.237    1959.042
Career_Contabilidad y fiscalización                                                                                                     78.6012    176.359      0.446      0.656    -267.059     424.262
Career_Criminología y criminalística                                                                                                 -1444.5908    415.099     -3.480      0.001   -2258.177    -631.005
Career_Deportes                                                                                                                      -2457.1307    739.190     -3.324      0.001   -3905.930   -1008.332
Career_Derecho                                                                                                                         294.7908    180.381      1.634      0.102     -58.753     648.335
Career_Dermatología                                                                                                                  -8921.0071   6301.816     -1.416      0.157   -2.13e+04    3430.444
Career_Desarrollo de hardware                                                                                                         3028.7908   3639.905      0.832      0.405   -4105.361    1.02e+04
Career_Desarrollo de software                                                                                                          465.7568    222.278      2.095      0.036      30.095     901.419
Career_Diagnóstico médico y tecnología del tratamiento                                                                                1352.8248    663.052      2.040      0.041      53.254    2652.395
Career_Diseño curricular y pedagogía                                                                                                 -1649.8705    304.268     -5.422      0.000   -2246.231   -1053.510
Career_Diseño industrial, de moda e interiores                                                                                        -658.6519    531.839     -1.238      0.216   -1701.047     383.743
Career_Diseño y comunicación gráfica y editorial                                                                                         1.6751    359.550      0.005      0.996    -703.037     706.387
Career_Ecología y ciencias ambientales                                                                                                -636.2911    781.760     -0.814      0.416   -2168.527     895.945
Career_Economía                                                                                                                       -219.0182    464.005     -0.472      0.637   -1128.459     690.423
Career_Electricidad y generación de energía                                                                                           -186.4404    365.910     -0.510      0.610    -903.618     530.737
Career_Electrónica, automatización y aplicaciones de la mecánica-eléctrica                                                             326.2540    231.289      1.411      0.158    -127.069     779.577
Career_Endocrinología                                                                                                                 1.035e+04   6301.733      1.642      0.100   -2000.981    2.27e+04
Career_Endodoncia                                                                                                                      344.9503   3641.920      0.095      0.925   -6793.150    7483.051
Career_Enfermería cardiovascular                                                                                                      4102.7031   6301.799      0.651      0.515   -8248.715    1.65e+04
Career_Enfermería crítica y cuidados intensivos                                                                                      -4011.6892   3155.580     -1.271      0.204   -1.02e+04    2173.193
Career_Enfermería en geriatría y gerontología                                                                                         2673.8324   6301.490      0.424      0.671   -9676.979     1.5e+04
Career_Enfermería general y obstetricia                                                                                                -96.2177    203.989     -0.472      0.637    -496.032     303.597
Career_Enfermería perinatal y pediátrica                                                                                             -5505.0651   6301.464     -0.874      0.382   -1.79e+04    6845.696
Career_Enfermería quirúrgica                                                                                                          3022.8528   2234.511      1.353      0.176   -1356.750    7402.455
Career_Estadística y actuaría                                                                                                         6535.9526   1533.448      4.262      0.000    3530.421    9541.484
Career_Estomatología y odontología general                                                                                            -386.8912    357.972     -1.081      0.280   -1088.510     314.728
Career_Farmacia                                                                                                                      -1043.1311    969.495     -1.076      0.282   -2943.324     857.062
Career_Filosofía y ética                                                                                                              -853.9734    875.065     -0.976      0.329   -2569.087     861.140
Career_Finanzas, banca y seguros                                                                                                      4557.8346    512.286      8.897      0.000    3553.763    5561.906
Career_Formación docente en cultura física                                                                                           -2579.3236    391.527     -6.588      0.000   -3346.710   -1811.938
Career_Formación docente en educación básica, nivel preescolar                                                                        -857.2890    294.645     -2.910      0.004   -1434.788    -279.790
Career_Formación docente en educación básica, nivel primaria                                                                          -361.0402    252.899     -1.428      0.153    -856.717     134.637
Career_Formación docente en educación básica, nivel secundaria                                                                        -494.5893    375.711     -1.316      0.188   -1230.977     241.798
Career_Formación docente en educación especial                                                                                       -1593.6859    537.530     -2.965      0.003   -2647.235    -540.137
Career_Formación docente en educación inicial                                                                                        -2163.8165    832.293     -2.600      0.009   -3795.097    -532.536
Career_Formación docente en educación media superior                                                                                    75.8421    992.621      0.076      0.939   -1869.678    2021.362
Career_Formación docente en educación para adultos                                                                                   -3781.8667   6300.231     -0.600      0.548   -1.61e+04    8566.477
Career_Formación docente en educación superior                                                                                       -1638.5686   1141.700     -1.435      0.151   -3876.280     599.143
Career_Formación docente en la enseñanza de idiomas                                                                                    613.7759   1072.671      0.572      0.567   -1488.640    2716.192
Career_Formación docente en otras asignaturas específicas                                                                              948.0414   1350.285      0.702      0.483   -1698.494    3594.577
Career_Formación docente para las artes                                                                                              -2523.3184   1177.061     -2.144      0.032   -4830.339    -216.298
Career_Física y astronomía                                                                                                            -427.2273   1352.451     -0.316      0.752   -3078.007    2223.553
Career_Gastronomía y servicios de alimentos                                                                                          -1496.7498    345.062     -4.338      0.000   -2173.066    -820.434
Career_Geriatría                                                                                                                     -3862.6045   2821.340     -1.369      0.171   -9392.382    1667.173
Career_Ginecología y obstetricia                                                                                                      5888.4763   1694.125      3.476      0.001    2568.020    9208.932
Career_Hematología                                                                                                                    7222.3572   4459.965      1.619      0.105   -1519.097     1.6e+04
Career_Historia y arqueología                                                                                                         1222.0851    780.789      1.565      0.118    -308.247    2752.418
Career_Horticultura                                                                                                                  -4719.9144   2231.603     -2.115      0.034   -9093.818    -346.011
Career_Hospitalidad y turismo                                                                                                        -1016.6216    373.462     -2.722      0.006   -1748.601    -284.642
Career_Industria de la alimentación                                                                                                   -826.4925    602.032     -1.373      0.170   -2006.464     353.479
Career_Industria de la minería, extracción y metalurgia                                                                               3073.3831    562.488      5.464      0.000    1970.916    4175.850
Career_Industria textil, del calzado y piel                                                                                          -1857.2169   1752.232     -1.060      0.289   -5291.561    1577.128
Career_Industrias de materiales diversos (cerámica, madera, plástico y vidrio)                                                       -4674.3030   2385.520     -1.959      0.050   -9349.882       1.276

## Classification Problem

In [35]:
new_employed = pd.read_csv('Data/new_employed.csv')
wk_incomes = pd.read_csv('Data/wk_incomes.csv')

In [36]:
new_employed['Monthly Income'].describe()

count    180370.000000
mean       7754.908993
std        6196.597671
min           0.000000
25%        5590.000000
50%        6880.000000
75%        8600.000000
max      300000.000000
Name: Monthly Income, dtype: float64

In [37]:
new_employed['Income Level']= new_employed['Monthly Income']
new_employed.head()

,Unnamed: 0,Residence,Gender,Age,Literacy,Scholarship,Career,Marital Status,Urban or Rural,Economic Zone,By Position,By Economic Sector,Monthly Income,Income Level
0,0,Ciudad de México,Hombre,59,Sí,Profesional,Biología,Está soltero(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880.0
1,2,Ciudad de México,Hombre,30,Sí,Profesional,Planes multidisciplinarios o generales del cam...,Está soltero(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,16000.0,16000.0
2,4,Ciudad de México,Hombre,42,Sí,Profesional,Telecomunicaciones,Está separado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880.0
3,5,Ciudad de México,Mujer,36,Sí,Profesional,Gastronomía y servicios de alimentos,Está casado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880.0
4,6,Ciudad de México,Hombre,43,Sí,Profesional,Hospitalidad y turismo,Está casado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880.0

In [38]:
level_1 = new_employed['Income Level'].quantile(.10)
level_2 = new_employed['Income Level'].quantile(.20)
level_3 = new_employed['Income Level'].quantile(.30)
level_4 = new_employed['Income Level'].quantile(.40)
level_5 = new_employed['Income Level'].quantile(.50)
level_6 = new_employed['Income Level'].quantile(.60)
level_7 = new_employed['Income Level'].quantile(.70)
level_8 = new_employed['Income Level'].quantile(.80)
level_9 = new_employed['Income Level'].quantile(.90)

In [40]:
new_employed.loc[(new_employed['Monthly Income'] <= level_1, 'Income Level')] = 'Level 1'
new_employed

,Unnamed: 0,Residence,Gender,Age,Literacy,Scholarship,Career,Marital Status,Urban or Rural,Economic Zone,By Position,By Economic Sector,Monthly Income,Income Level
0,0,Ciudad de México,Hombre,59,Sí,Profesional,Biología,Está soltero(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880
1,2,Ciudad de México,Hombre,30,Sí,Profesional,Planes multidisciplinarios o generales del cam...,Está soltero(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,16000.0,16000
2,4,Ciudad de México,Hombre,42,Sí,Profesional,Telecomunicaciones,Está separado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880
3,5,Ciudad de México,Mujer,36,Sí,Profesional,Gastronomía y servicios de alimentos,Está casado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880
4,6,Ciudad de México,Hombre,43,Sí,Profesional,Hospitalidad y turismo,Está casado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,6880
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180365,389425,Zacatecas,Hombre,62,Sí,Primaria,NaN,Está casado(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Construcción,7740.0,7740
180366,389428,Zacatecas,Mujer,31,Sí,Preparatoria o bachillerato,NaN,Está viudo(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,7740.0,7740
180367,389429,Zacatecas,Mujer,18,Sí,Preparatoria o bachillerato,NaN,Está soltero(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Comercio,7955.0,7955
180368,389430,Zacatecas,Hombre,54,Sí,Primaria,NaN,Está casado(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores por cuenta propia,Servicios,6880.0,6880
180369,389432,Zacatecas,Hombre,67,Sí,Primaria,NaN,Está casado(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores por cuenta propia,Agropecuario,583.0,Level 1

In [44]:
new_employed.loc[(new_employed['Monthly Income'] <= level_2, 'Income Level')] = 'Level 2'
new_employed.loc[(new_employed['Monthly Income'] <= level_3, 'Income Level')] = 'Level 3'
new_employed.loc[(new_employed['Monthly Income'] <= level_4, 'Income Level')] = 'Level 4'
new_employed.loc[(new_employed['Monthly Income'] <= level_5, 'Income Level')] = 'Level 5'
new_employed.loc[(new_employed['Monthly Income'] <= level_6, 'Income Level')] = 'Level 6'
new_employed.loc[(new_employed['Monthly Income'] <= level_7, 'Income Level')] = 'Level 7'
new_employed.loc[(new_employed['Monthly Income'] <= level_8, 'Income Level')] = 'Level 8'
new_employed.loc[(new_employed['Monthly Income'] <= level_9, 'Income Level')] = 'Level 9'
new_employed.loc[(new_employed['Monthly Income'] > level_9, 'Income Level')] = 'Level 10'

In [45]:
new_employed

,Unnamed: 0,Residence,Gender,Age,Literacy,Scholarship,Career,Marital Status,Urban or Rural,Economic Zone,By Position,By Economic Sector,Monthly Income,Income Level
0,0,Ciudad de México,Hombre,59,Sí,Profesional,Biología,Está soltero(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,Level 9
1,2,Ciudad de México,Hombre,30,Sí,Profesional,Planes multidisciplinarios o generales del cam...,Está soltero(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,16000.0,Level 10
2,4,Ciudad de México,Hombre,42,Sí,Profesional,Telecomunicaciones,Está separado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,Level 9
3,5,Ciudad de México,Mujer,36,Sí,Profesional,Gastronomía y servicios de alimentos,Está casado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,Level 9
4,6,Ciudad de México,Hombre,43,Sí,Profesional,Hospitalidad y turismo,Está casado(a),Muestra urbana,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,6880.0,Level 9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180365,389425,Zacatecas,Hombre,62,Sí,Primaria,NaN,Está casado(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Construcción,7740.0,Level 9
180366,389428,Zacatecas,Mujer,31,Sí,Preparatoria o bachillerato,NaN,Está viudo(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Servicios,7740.0,Level 9
180367,389429,Zacatecas,Mujer,18,Sí,Preparatoria o bachillerato,NaN,Está soltero(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores subordinados y remunerados,Comercio,7955.0,Level 9
180368,389430,Zacatecas,Hombre,54,Sí,Primaria,NaN,Está casado(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores por cuenta propia,Servicios,6880.0,Level 9
180369,389432,Zacatecas,Hombre,67,Sí,Primaria,NaN,Está casado(a),Muestra complemento y rural,Zona 2 Resto del paÃ­s,Trabajadores por cuenta propia,Agropecuario,583.0,Level 9

In [46]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder
from sklearn import tree

In [51]:
y = new_employed['Income Level']
X = new_employed.drop(columns=['Monthly Income', 'Income Level'], axis=1)

rel_columns = ['Age','Gender', 'Literacy', 'Scholarship','Career', 'Marital Status', 'Urban or Rural', 'Residence','Economic Zone', 'By Position','By Economic Sector']
X = pd.get_dummies(X[rel_columns], drop_first=True, dtype=float)

scaler = MinMaxScaler()
X=pd.DataFrame(scaler.fit_transform(X),
            columns=X.columns, index=X.index) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= 42)

In [52]:
clf = DecisionTreeClassifier(criterion='entropy')

clf.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [54]:
y_preds = clf.predict(X_test)

print('Accuracy: ', accuracy_score(y_test, y_preds))

Accuracy:  0.8546875866274879

## with known incomes

In [59]:
wk_incomes['Income Level']= wk_incomes['Monthly Income']

level_1 = wk_incomes['Income Level'].quantile(.10)
level_2 = wk_incomes['Income Level'].quantile(.20)
level_3 = wk_incomes['Income Level'].quantile(.30)
level_4 = wk_incomes['Income Level'].quantile(.40)
level_5 = wk_incomes['Income Level'].quantile(.50)
level_6 = wk_incomes['Income Level'].quantile(.60)
level_7 = wk_incomes['Income Level'].quantile(.70)
level_8 = wk_incomes['Income Level'].quantile(.80)
level_9 = wk_incomes['Income Level'].quantile(.90)

wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_1, 'Income Level')] = 'Level 1'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_2, 'Income Level')] = 'Level 2'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_3, 'Income Level')] = 'Level 3'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_4, 'Income Level')] = 'Level 4'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_5, 'Income Level')] = 'Level 5'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_6, 'Income Level')] = 'Level 6'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_7, 'Income Level')] = 'Level 7'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_8, 'Income Level')] = 'Level 8'
wk_incomes.loc[(wk_incomes['Monthly Income'] <= level_9, 'Income Level')] = 'Level 9'
wk_incomes.loc[(wk_incomes['Monthly Income'] > level_9, 'Income Level')] = 'Level 10'

y = wk_incomes['Income Level']
X = wk_incomes.drop(columns=['Monthly Income', 'Income Level'], axis=1)

rel_columns = ['Age','Gender', 'Literacy', 'Scholarship','Career', 'Marital Status', 'Urban or Rural', 'Residence','Economic Zone', 'By Position','By Economic Sector']
X = pd.get_dummies(X[rel_columns], drop_first=True, dtype=float)

scaler = MinMaxScaler()
X=pd.DataFrame(scaler.fit_transform(X),
            columns=X.columns, index=X.index) 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state= 42)

clf = DecisionTreeClassifier(criterion='entropy')

clf.fit(X_train, y_train)

y_preds = clf.predict(X_test)

print('Accuracy: ', accuracy_score(y_test, y_preds))

Accuracy:  0.858159029008118